language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: OODth6dPqTP7oH90fFLHQ9hozBG5vxL9S7pprN8JYMvOCKw3pWul/rfHS6Q9XUtbkx/We8E9+/mxN6zETcWizWZ3ziAkH3Y0tteABWzfXUDCL4vGeIAgyjGzMhmH8e/PDvYs1qto9I8aahhHe+pyVM8104oBiVugxDC4Ittxtv9IQcuElBT85tNVA8U7wny1LtBa1snoHm8qLh9Ov0X+82C4xUbW3JHzH1sbWIkEdv4effkBOtE1Q+khhmbpLpFYyD+1AGdyzKfrtyuFjWYZstohAFFBMkAF3mnOuKCU+v/KkJ9QushbCyO1du2NqvZCkWU4Wz28q05FokFTRaFwTuNdHoLha2SmTs+zWiHTn7/nWf9tj9+7G4sxomKq9QyHz/jhieSIw9uqX/yesVvd+G7IaRw0qfrxQJBAhOe7PNrpfs3z4ueWjdrs/hS4vS7sD4+DrPCHNfo38D7H1K7VSKLXw8KaF24Qaj5QeyCN/pNhJ26WS+X9PormMcP5c28yk6ZUbKsD3yewoT7xzhFmEi0BX2zc41Oxp7ifc+xqMd0zJd4CjXCWhZSCbG0B3JCA/sqTF8DvGQpAMq5TqDPttCypF/yk19ZtfWULT5M/eaHZN2vC2vgwPNnsQ2zhTAlX9xaRyQEPIeTuwXoQler1A4bp4rdDvIFyTY6aLFGWgqo=
  app: love-your-tech-stack
  on:
    repo: Pallandor/coding-challenge
